# Generated by Django 4.1.3 on 2022-12-01 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='numero',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
